### ISSUE TITLE
Aborted message with AX3600 and China 1.0.424 rom

### ISSUE THREAD

**Issue by FaserF** [dmamontov/hass-miwifi#1]
I am unable to connect my AX3600 router with this integration.
I am only getting an „aborted“ message while adding the integration in the GUI.
Legacy yaml doesn’t seem to work too.
No error log.

password and IP is definitely correct.
China Rom (stable) with Root SSH Access if that matters.
The official Xiaomi device tracker integration seems also not to work, but I don’t see any log messages.

**Comment by dmamontov** [comment]
> I am unable to connect my AX3600 router with this integration.
> I am only getting an „aborted“ message while adding the integration in the GUI.
> Legacy yaml doesn’t seem to work too.
> No error log.
> 
> password and IP is definitely correct.
> China Rom (stable) with Root SSH Access if that matters.
> The official Xiaomi device tracker integration seems also not to work, but I don’t see any log messages.

http://<your ip>/cgi-bin/luci/;stok=<your stok>/api/xqsystem/init_info

Enter the following url into the browser only replace <your ip> and <your stok>. Send here what was returned in the answer.

<your stok> can be obtained after authorization. it will be in the browser bar

**Comment by FaserF** [comment]
Here we go:

`{"romversion":"1.0.424","countrycode":"EU","code":0,"id":"29010/E0RV93207","routername":"Xiaomi_ABD8","inited":1,"connect":0,"routerId":"a2bbb65d-c69b-2002-1419-872e306b0941","model":"xiaomi.router.r3600","hardware":"R3600","bound":0,"language":"zh_cn","modules":{"replacement_assistant":"1"}}`

**Comment by dmamontov** [comment]
and now try to call the same url call through curl from the server. api works for you, but there is a suspicion that the request does not pass from the hass server.

**Comment by FaserF** [comment]
You were right. The issue was that the router was in WAN mode and not in LAN to LAN mode.
now it is working great!
