### ISSUE TITLE
[FEATURE REQUEST] Total data usage

### ISSUE THREAD

**Issue by michaldz** [dmamontov/hass-miwifi#100]
Hi, Is it possible in somehow to add total data usage?
In android mobile app there is this information(for specyfic device) and probably it's daily counter
I am wondering if it is possible 
![image](https://user-images.githubusercontent.com/1795010/201470897-e01a3d11-7b7d-4bc8-998f-1af20c91c946.png)

**Comment by dmamontov** [comment]
@michaldz Unfortunately, this is not in the local API (only in the cloud and private).
