### ISSUE TITLE
[FEATURE REQUEST] Status of internet connection

### ISSUE THREAD

**Issue by geobar78** [dmamontov/hass-miwifi#113]
hi, is it possible to retrieve the status of the internet connection?
I would like to be able to start specific automations in the event of an internet outage (presence detection, for example, because no one connects via wifi and therefore the heating management is switch off, although the heating management works locally, so when I am there I can force locally a boolean input to simulate a presence, but when I'm not there... my wife is not happy :-) )
Thanks in advance
Best Regards.

![no internet](https://user-images.githubusercontent.com/75928935/213848899-969d9849-bde1-4330-9663-4ca2dbb48421.jpg)

**Comment by dmamontov** [comment]
@geobar78 It seems to be binary_sensor.miwifi_00_00_00_00_00_00_wan_state and displays the connection, doesn't it?

**Comment by geobar78** [comment]
hooo thank you very much for your return, I'm ashamed to have been so blind, I'm going to hide in a very small hole.
