### ISSUE TITLE
Add supports R4AV2

### ISSUE THREAD

**Issue by Vlad-Yevs** [dmamontov/hass-miwifi#114]
Check list:
 * xqsystem/login: 🟢
 * xqsystem/init_info: 🟢
 * misystem/status: 🟢
 * xqnetwork/mode: 🟢
 * xqsystem/vpn_status: 🟢
 * misystem/topo_graph: 🟢
 * xqsystem/check_rom_update: 🟢
 * xqnetwork/wan_info: 🟢
 * misystem/led: 🟢
 * xqnetwork/wifi_detail_all: 🟢
 * xqnetwork/wifi_diag_detail_all: 🟢
 * xqnetwork/avaliable_channels: 🟢
 * xqnetwork/wifi_connect_devices: 🟢
 * misystem/devicelist: 🟢
 * xqnetwork/wifiap_signal: 🟢
 * misystem/newstatus: 🟢
 * xqsystem/reboot: ⚪
 * xqsystem/upgrade_rom: ⚪
 * xqsystem/flash_permission: ⚪
 * xqnetwork/set_wifi: ⚪
 * xqnetwork/set_wifi_without_restart: ⚪

**Comment by dmamontov** [comment]
Added in release https://github.com/dmamontov/hass-miwifi/releases/tag/v3.0.0

@Vlad-Yevs thanks.

**Comment by VINCE-HA** [comment]
but not supported on supports R4ACv2
