### ISSUE TITLE
Cero devices detected

### ISSUE THREAD

**Issue by gurues** [dmamontov/hass-miwifi#12]
Hello
I have installed your integration hass-miwifi but it not run completely. It nor detect my connected devices, all it are 0. I have reset my router with your integratition  but happens the same. I have two router Xiaomi AX1800.
Please, You can help me?
![pp](https://user-images.githubusercontent.com/35085918/147363337-bcae213e-d3c1-40ae-b0f7-68a9639da971.JPG)
![rr](https://user-images.githubusercontent.com/35085918/147363350-14ee6b97-8d2e-4d3d-8b78-d678188857fe.JPG)

Thanks

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v1.3.2

Try to update
