### ISSUE TITLE
Turning Wifi On/Off

### ISSUE THREAD

**Issue by alirezadigi** [dmamontov/hass-miwifi#13]
Hi! Sorry Can i turn wifi on/off via this intergration?

**Comment by alirezadigi** [comment]
https://github.com/Veeenz/MiWifi4-Router-Api

with this library it seems thats possible

**Comment by dmamontov** [comment]
I will add in version 2.0. it will be released at the beginning of the year.

**Comment by dmamontov** [comment]
Fixed in release: https://github.com/dmamontov/hass-miwifi/releases/tag/v2.0.0b
