### ISSUE TITLE
Getting "aborted" message when trying to add (AX9000)

### ISSUE THREAD

**Issue by Tsury** [dmamontov/hass-miwifi#17]
I did upgrade the firmware to the Chinese developer firmware (1.0.140). Do I need to rollback to 1.0.108?

```
{"romversion":"1.0.140","countrycode":"CN","code":0,"id":"30320/F0Z735418","routername":"Whatever","inited":1,"connect":0,"routerId":"b8e6247f-0668-9f42-3889-d52ac8228556","maccel":"1","model":"xiaomi.router.ra70","hardware":"RA70","bound":0,"language":"zh_cn","modules":{"replacement_assistant":"1"}}
```

```
This error originated from a custom integration.

Logger: custom_components.miwifi.config_flow
Source: custom_components/miwifi/config_flow.py:72
Integration: MiWiFi (documentation, issues)
First occurred: 9:27:40 PM (2 occurrences)
Last logged: 9:29:28 PM

Error setting up MiWiFi API: LuciConnectionError()
```

**Comment by dmamontov** [comment]
I have a link to my Telegram in my profiles, could you write to me, and I will ask you to make a few requests to the router in order to understand what has changed in the new version and add support. Unfortunately I don't have them myself.

**Comment by brunob78** [comment]
I have the same issue when trying to add my Xiaomi 4A router. The error was "Invalid IP" and in the log I have the same message than below.

**Comment by dmamontov** [comment]
Turn on debug mode and try again, the lair will be bigger.

**Comment by dmamontov** [comment]
@Tsury Good afternoon! I wrote to you on telegram, I'm waiting for an answer.

**Comment by Tsury** [comment]
Thank you @dmamontov for the help!

**Comment by dmamontov** [comment]
@Tsury 

It seems that I found similar methods in the firmware for 5g game devices. Can you check?

/api/misystem/get_iotdev_status
/api/xqnetwork/get_netmode
/api/xqnetwork/get_transport_list
