### ISSUE TITLE
MiWiFi no

### ISSUE THREAD

**Issue by kusok18** [dmamontov/hass-miwifi#18]
<img width="1677" alt="Снимок экрана 2022-02-26 в 00 19 42" src="https://user-images.githubusercontent.com/53447958/155795499-11b40291-94b1-447f-9dd0-51f4248a4a02.png">
<img width="1673" alt="Снимок экрана 2022-02-26 в 00 20 10" src="https://user-images.githubusercontent.com/53447958/155795728-883f4647-3ca2-4b5e-9732-c96a7c1fd636.png">

Settings > Integrations > Plus > MiWiFi

no integration.
Where to look for it?
how to install it correctly?

**Comment by dmamontov** [comment]
try downloading again. I don't see a problem with the component. are your logs empty?
