### ISSUE TITLE
[Feature Request] Option to control WiFi range through HA

### ISSUE THREAD

**Issue by FaserF** [dmamontov/hass-miwifi#2]
Thank you again for your awesome work. The integration is working so great for me.

i am only missing one option, so i am asking if it is possible:
I am using the Chinese Firmware which allows me to use higher WiFi ranges. I don’t know if these higher values are bad or good, but I would feel better if I could automate the WiFi range via HA.
MiWifi offers three options: short, middle or „through the wall“
I would like to automate these options that HA could set it at night to short and over the day when I need it to „through the wall“.

Does the Luci API allow access to these values? For example to create a HA Switch with the value „on“ for „through the wall“ and off for short? Or even better a input_selector

thank you in advance

**Comment by dmamontov** [comment]
I'm working on a new version now. I'm thinking of adding the possibility of scanning ranges and adding a service to install them. I think there will be a release in May. I also want to add a built-in speed test.

**Comment by FaserF** [comment]
You are awesome! 🙂

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.2.0

You can try)

**Comment by FaserF** [comment]
Works great! Thank you.
In my router settings I can define it a bit more detailed, but to access it via HA, this is great like it is.
![image](https://user-images.githubusercontent.com/12374134/162423951-ec896f0d-adea-4de4-97a0-0f857d0f9e31.png)

**Comment by dmamontov** [comment]
Do you remember the router model?

**Comment by FaserF** [comment]
AX3600 (China Rom)

**Comment by dmamontov** [comment]
Cool. I have the same one and there are only 3 options) True, it was European and I stitched it into Chinese. Otherwise, the speed was cut.

**Comment by FaserF** [comment]
maybe these options then come because I have rooted my firmware.

Then wifi range is way better with the China rom :)

**Comment by dmamontov** [comment]
@FaserF Can you give me the firmware version? I'll take it apart and see what methods there are in order to pull out the list.

**Comment by FaserF** [comment]
Sure, 1.1.19 (should be the latest one)
