### ISSUE TITLE
Add miwifi logo

### ISSUE THREAD

**Issue by hudsonbrendon** [dmamontov/hass-miwifi#20]
The miwifi logo could be added to the integration, it would look much better.

![image](https://user-images.githubusercontent.com/5201888/158642515-f25e1ddd-17ae-4c05-addc-53b5fe5d8975.png)

could be this logo that is their official:

![miwifi](https://user-images.githubusercontent.com/5201888/158642876-f12c914c-60c5-4c42-9d79-9c0eab740105.png)

**Comment by SPEC1AL1ST** [comment]
Good idea

**Comment by dmamontov** [comment]
Made PRs. We wait.

https://github.com/home-assistant/brands/pull/3300
https://github.com/home-assistant/wheels-custom-integrations/pull/601

**Comment by dmamontov** [comment]
Fixed in release: https://github.com/dmamontov/hass-miwifi/releases/tag/v2.0.0b
