### ISSUE TITLE
Add supports R4A

### ISSUE THREAD

**Issue by velijv** [dmamontov/hass-miwifi#24]
Check list:
 * xqsystem/login: 🟢
 * xqsystem/init_info: 🟢
 * xqsystem/reboot: 🟢
 * misystem/status: 🟢
 * xqnetwork/mode: 🟢
 * misystem/topo_graph: 🟢
 * xqnetwork/wan_info: 🟢
 * misystem/led: 🟢
 * xqnetwork/wifi_detail_all: 🟢
 * xqnetwork/wifi_connect_devices: 🟢
 * misystem/devicelist: 🟢
 * misystem/newstatus: 🟢

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.0.3b

Thanks)
