### ISSUE TITLE
Reboot of the Router creates new entites in HA

### ISSUE THREAD

**Issue by FaserF** [dmamontov/hass-miwifi#3]
It looks like that every reboot of the MiWifi Router creates new switches and sensors. 
This blows HA and syncs not working buttons to my Google Home. 

This looks like a bug or am I missing something?

![image](https://user-images.githubusercontent.com/12374134/118768451-4b61f380-b87f-11eb-9f98-d2ebd2773124.png)

**Comment by dmamontov** [comment]
It’s very strange, I don’t repeat this. logically, a unique identifier is generated based on the name of the router and the name of the button.

![image](https://user-images.githubusercontent.com/5955726/118769400-cbd92200-b888-11eb-9e1b-96921799c4bd.png)

What version of hass do you have? and what version of the component?

**Comment by FaserF** [comment]
Sorry for the less informations.

Home Assistant OS 5.13
core-2021.5.3
supervisor-2021.04.3
Latest hass-miwifi version: 1.1.1

And one thing to add:
I have two xiaomi router, one stays on most of the time if there is no electricity error. The other one is only being turned on one to two times a week.
Looks like the one thats only turned on sometimes creates the new entities. The other one that is being restarted sometime seems not to create new entities.

**Comment by dmamontov** [comment]
I will restart now

**Comment by FaserF** [comment]
Maybe the difference is:

Router 1: Is turned on when HA was restarted
Router 2: is most likely turned off when HA was restarted and will be turned on some hours/days later -> Could this generate a new ID?

Thank you already for your Help!

**Comment by dmamontov** [comment]
I do not see from the image that the name of the printer is changing. As soon as I get home, I'll try to add logging and download the beta version, let's see what you get

**Comment by FaserF** [comment]
![image](https://user-images.githubusercontent.com/12374134/126600275-e13efb69-a8ab-4240-ab42-32236e7286b9.png)

Here is a screenshot to show the issue a bit better. The ones marked with green is my Xiaomi AX3600 router which is connected 24/7 and in router mode and works as intended and correctly.

The marked ones in red is my Xiaomi AX1800 router which is in Mesh AP mode and is connected only about twice a week for some hours and then gets cutted from the power. 
As you can see it seems to create a new entity on every new start from the router.

What exactly is the primary ID for you addon to detect that the router should be the same one and not a "new one"? The MAC Adress?

**Comment by areyoufserious** [comment]
Hi
I have the same case as @FaserF has

Router Redmi 6
![image](https://user-images.githubusercontent.com/77510096/126934739-84260559-fc86-4b72-bc4a-c5499ca35276.png)

Option "Forced booting of devices in repeater mode [PRO]" set
FYI Redmi 6 works as access point

**Comment by dmamontov** [comment]
> What exactly is the primary ID for you addon to detect that the router should be the same one and not a "new one"? The MAC Adress?

Mac + IP, I got out of this situation by specifying a static ip in the main router on the poppy mesh

**Comment by dmamontov** [comment]
> Option "Forced booting of devices in repeater mode [PRO]" set
> FYI Redmi 6 works as access point

Refine your hass version

**Comment by areyoufserious** [comment]
> > Option "Forced booting of devices in repeater mode [PRO]" set
> > FYI Redmi 6 works as access point
> 
> Refine your hass version

I’m sorry, please describe how to do it

**Comment by dmamontov** [comment]
> > > Option "Forced booting of devices in repeater mode [PRO]" set
> > > FYI Redmi 6 works as access point
> > 
> > 
> > Refine your hass version
> 
> I’m sorry, please describe how to do it
> 
> That what I have in supervisor menu
> ![image](https://user-images.githubusercontent.com/77510096/126947894-c8b65d5f-4e07-4b78-8ee1-352feb55de07.png)

I have an older one, I'll try to update.

**Comment by FaserF** [comment]
Just for extra information. I am running the latest HA Versions available:

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 915
Installed Repositories | 20

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 234.0 GB
disk_used | 47.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | SSH & Web Terminal (9.0.0), ADB - Android Debug Bridge (0.8.0), AdGuard Home (4.1.6), Home Assistant Google Drive Backup (0.104.3), MariaDB (2.4.0), Mosquitto broker (6.0.1), AirCast (3.1.1), Assistant Relay (0.7.4), Visual Studio Code (3.6.0), Bitwarden (Vaultwarden) (0.12.0), Google Assistant SDK (2.5.0), Nextcloud (20.0.3), heimdall (0.1.1), Nginx Proxy Manager (0.11.0), Wiki.JS (1.1.0), Apache2 Minimal with MariaDB Client (2.1.0), Bash Script Executer (1.2.0), xqrepack (1.2.0), Freenom-dns-updater (1.0.0), Switch LAN Play Server (1.2.0), Switch LAN Play Client (1.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 9
views | 12
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by dmamontov** [comment]
> Just for extra information. I am running the latest HA Versions available:
> 
> ## System Health
> version	core-2021.7.4
> installation_type	Home Assistant OS
> dev	false
> hassio	true
> docker	true
> virtualenv	false
> python_version	3.9.5
> os_name	Linux
> os_version	5.10.17-v8
> arch	aarch64
> timezone	Europe/Berlin
> Home Assistant Community Store
> Home Assistant Supervisor
> Lovelace
> Spotify

A debug does not swear?

**Comment by FaserF** [comment]
if it is for any help I can enable debugging, if you tell me what you need.
Right now it was disabled all the time

**Comment by areyoufserious** [comment]
@dmamontov hi
are there any updates? What help do you need?

**Comment by areyoufserious** [comment]
Thanks for your efforts!

according to description I deleted all entities by myself, then I launched service

also I deleted all related files in .storage folder and reinstalled integration 

Fix doesn’t work, issue still reproduces

**Comment by dmamontov** [comment]
> Fix doesn’t work, issue still reproduces

Do you have static ip assigned to all devices?

**Comment by FaserF** [comment]
I can also confirm that it still sadly doesnt work. Issue stays the same.

I am using no static IP, but the IP has not changed.

**Comment by dmamontov** [comment]
This principle has never happened to me. But it is from your images above that I see that the name of the router has changed inside. Which is very strange.

**Comment by FaserF** [comment]
The name stays the same, only a new number gets added at the end (_2   _3   _4 and so on)
IP stays the same and MAC shouldn't change too.

But ony thing to mention: My both Xiaomi Routers are running in mesh mode. The one thats making trouble is the mesh client (not the mesh master).

**Comment by dmamontov** [comment]
And on which entities?

**Comment by areyoufserious** [comment]
FYI: my routers don't connect over mesh

structure of entitiies
![image](https://user-images.githubusercontent.com/77510096/129537469-0d9e4e17-c145-4b61-9528-c4247d42e2b6.png)

**Comment by FaserF** [comment]
> And on which entities?

every entity for me

**Comment by areyoufserious** [comment]
> > And on which entities?
> 
> every entity for me

the same for me

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v1.2.1b

Try to put with the same actions

**Comment by FaserF** [comment]
Seems to work. Didn’t do a extended testing but so far it works and no new entities get created. 
thank you already!
