### ISSUE TITLE
New error version 2.0.5 device tracker

### ISSUE THREAD

**Issue by Mick51** [dmamontov/hass-miwifi#30]
Cette erreur provient d'une intégration personnalisée

Logger: homeassistant
Source: custom_components/miwifi/device_tracker.py:383
Integration: MiWiFi (documentation, issues)
First occurred: 23:41:59 (27 occurrences)
Last logged: 23:41:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/miwifi/device_tracker.py", line 383, in check_ports
    result = sock.connect_ex((self.ip_address, port))
TypeError: str, bytes or bytearray expected, not NoneType

**Comment by dmamontov** [comment]
What version of python do you have?

**Comment by Mick51** [comment]
> What version of python do you have?

## System Health

version | core-2022.3.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4751
Installed Version | 1.24.3
Stage | running
Available Repositories | 1078
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 111.1 GB
disk_used | 9.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.14.0), File editor (5.3.3), RPC Shutdown (2.2), Samba share (9.5.1), ESPHome (2022.3.1), Home Assistant Google Drive Backup (0.106.2), Terminal & SSH (9.3.0), Glances (0.15.0), Check Home Assistant configuration (3.10.0), SQLite Web (3.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 30
views | 8
mode | storage

</details>

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.0.7

**Comment by Mick51** [comment]
> https://github.com/dmamontov/hass-miwifi/releases/tag/v2.0.7

Problem solved, thanks for the fast fix.  😉
