### ISSUE TITLE
Error adding entities for domain

### ISSUE THREAD

**Issue by velijv** [dmamontov/hass-miwifi#33]
`Error adding entities for domain switch with platform miwifi
11:13:29 – (ERROR) Switch - message first occurred at 11:13:29 and shows up 2 times
Error adding entities for domain button with platform miwifi
11:13:29 – (ERROR) Button - message first occurred at 11:13:29 and shows up 2 times
Error adding entities for domain light with platform miwifi
11:13:29 – (ERROR) Light - message first occurred at 11:13:29 and shows up 2 times
Error adding entities for domain sensor with platform miwifi
11:13:29 – (ERROR) Sensor - message first occurred at 11:13:29 and shows up 2 times
Error adding entities for domain binary_sensor with platform miwifi
11:13:29 – (ERROR) Binary sensor - message first occurred at 11:13:29 and shows up 2 times`

`Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:383
Integration: Switch (documentation, issues)
First occurred: 11:13:29 (2 occurrences)
Last logged: 11:13:29

Error adding entities for domain switch with platform miwifi
Error while setting up miwifi platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
`

Used to have a button for reboot, light for led control, and uptime sensor.

**Comment by dmamontov** [comment]
What version of HASS do you have?

**Comment by dmamontov** [comment]
In the minimum version for the component, everything is correct and is https://github.com/home-assistant/core/blob/2022.3.0/homeassistant/const.py#L751

**Comment by dmamontov** [comment]
Fix - https://github.com/dmamontov/hass-miwifi/releases/tag/v2.1.0
The problem in HASS was (((
