### ISSUE TITLE
Platform miwifi does not generate unique IDs

### ISSUE THREAD

**Issue by IvAn-source-git** [dmamontov/hass-miwifi#35]
I have 2 miwifi.

Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:593
Integration: Отслеживание устройств (documentation, issues)
First occurred: 16:41:25 (18 occurrences)
Last logged: 16:41:25

Platform miwifi does not generate unique IDs. ID miwifi-xx:xx:xx:xx:xx:xx is already used by device_tracker.miwifi_xx_xx_xx_xx_xx_xx - ignoring device_tracker.miwifi_xx_xx_xx_xx_xx_xx

**Comment by dmamontov** [comment]
This happens and it's not scary, updaters intersect. Still wondering how to get them out of sync.

**Comment by dmamontov** [comment]
Found one option. I will test and push)

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.1.3

Thanks)
