### ISSUE TITLE
New error version 2.1.1

### ISSUE THREAD

**Issue by Mick51** [dmamontov/hass-miwifi#38]
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.miwifi.updater
Source: custom_components/miwifi/updater.py:254
Integration: MiWiFi (documentation, issues)
First occurred: 23:54:38 (1 occurrences)
Last logged: 23:54:38

Error connecting to router (attempt #1 of 10): LuciConnectionException()

**Comment by dmamontov** [comment]
Increase the timeout, this is a normal error.

**Comment by dmamontov** [comment]
Replaced with warning, so as not to confuse)
