### ISSUE TITLE
[question] Router support with custom firmware

### ISSUE THREAD

**Issue by sqrddrv** [dmamontov/hass-miwifi#43]
The question is very stupid. Is this integration suitable for a Xiaomi Mi Router 4A Giga with firmware OpenWrt 21.02.2?

I saw this message and thought that everything should work, but alas no.
` Many more Xiaomi and Redmi routers supported by MiWiFi (OpenWRT - Luci API)`

The first time the integration cursed for the wrong IP, and later it showed like this:
![image](https://user-images.githubusercontent.com/67025885/162840456-a8702f1c-d35c-474e-89ef-4150e03f8231.png)

I'm a newbie, and if I misunderstood something, I'm sorry.

**Comment by dmamontov** [comment]
Unfortunately, only original miwifi firmware. they have a specific API.
