### ISSUE TITLE
Unable to get AX6 to work proprely with that

### ISSUE THREAD

**Issue by DavidFFerreira** [dmamontov/hass-miwifi#45]
Unable to get AX6 to work proprely with that

![image](https://user-images.githubusercontent.com/32928749/162944654-910a2dca-3e39-4fae-99fe-debe43f603fe.png)
![image](https://user-images.githubusercontent.com/32928749/162944727-931ed51f-4768-47af-9b19-1b2fa2806543.png)
![image](https://user-images.githubusercontent.com/32928749/162944750-01107190-a85f-4d42-a83d-7a37c70350dc.png)

**Comment by dmamontov** [comment]
Enable debug mode and send the log. Preferably a file. Thank you.

**Comment by dmamontov** [comment]
The abandoned information was not received.
