### ISSUE TITLE
Guest Wi-Fi network

### ISSUE THREAD

**Issue by fcoval** [dmamontov/hass-miwifi#47]
Good morning,
Congratulations for this project. 
I would like to know if for future revisions it would be possible to add the guest Wi-Fi network (to activate and deactivate it)
, many thanks.

**Comment by dmamontov** [comment]
Good afternoon! I think it's possible. I will write to you when it will be possible to test. Most likely it will be a beta version.

**Comment by fcoval** [comment]
> Good afternoon! I think it's possible. I will write to you when it will be possible to test. Most likely it will be a beta version.

Perfect, many thanks again.

**Comment by dmamontov** [comment]
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.5.0

@fcoval enjoy)
