### ISSUE TITLE
[BUG] 5G Wi-Fi band switch does not work well

### ISSUE THREAD

**Issue by fcoval** [dmamontov/hass-miwifi#51]
**Describe the bug**
Hi, thank you very much for this new version. I have updated to version 2.5.0 but I see that the 5G Wi-Fi band switch does not work well, it is always ON even if the network is turned off.  (switch.miwifi_XX_XX_XX_XX_XX_XX_wifi_5g)
Thank you.

 - HASS version: 2022.4.0
 - Home Assistant Core 2022.4.6
 - Home Assistant Operating System 7.6
 - Component version 2.5.0
 - Router model AX3600
 - Router firmware version 1.1.19 CN

**Comment by dmamontov** [comment]
Please provide diagnostic information. Instruction received via GUI: https://github.com/dmamontov/hass-miwifi#diagnostics

**Comment by fcoval** [comment]
File:
[config_entry-miwifi-bfa0065abdd52daecf38b0a100f10c6c.json - EDITED MACS.txt](https://github.com/dmamontov/hass-miwifi/files/8542476/config_entry-miwifi-bfa0065abdd52daecf38b0a100f10c6c.json.-.EDITED.MACS.txt)

![HA](https://user-images.githubusercontent.com/73198468/164754444-df76a341-cfa9-4de3-b1c2-bb40f14b2255.JPG)
![Router-Wifi-Configuration](https://user-images.githubusercontent.com/73198468/164754451-1fdbc194-9e6b-4b5b-8033-f412a1fe0672.jpg)

**Comment by dmamontov** [comment]
@fcoval I will need time to study the logs

**Comment by dmamontov** [comment]
@fcoval https://github.com/dmamontov/hass-miwifi/releases/tag/v2.5.2

Check out this release.

If it doesn't help, then you need information from api with wifi enabled.

http://192.168.31.1/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_detail_all

http://192.168.31.1/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_diag_detail_all

**Comment by fcoval** [comment]
Hi Dimitri,
The switch works in terms of sending the order to the router to turn the Wi-Fi network ON and OFF, but after a few seconds/minutes, you see, for example, that it has acted by turning off the Wi-Fi network in the router, but, in Home Assistant you see that the switch continues to report which network is always ON state. It does not work correctly, and it does not only happen in the 5G Wi-Fi network, also in the 2.4G network, it happens to both switches.

I pass the information with both networks enabled ( for 2.4G and 5G):

**http://192.168.31.1/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_detail_all**

{"bsd":0,"info":[{"ifname":"wl1","channelInfo":{"bandwidth":"0","bandList":["20","40"],"channel":11},"encryption":"psk2","bandwidth":"0","kickthreshold":"0","status":"1","mode":"Master","ssid":"RedSinInternet","weakthreshold":"0","device":"wifi1.network1","ax":"1","hidden":"0","password":"**REDACTED**","channel":"11","txpwr":"max","weakenable":"0","txbf":"3","signal":-97},{"ifname":"wl0","channelInfo":{"bandwidth":"0","bandList":["20","40","80","160"],"channel":48},"encryption":"mixed-psk","bandwidth":"0","kickthreshold":"0","status":"1","mode":"Master","ssid":"RedSinInternet5","weakthreshold":"0","device":"wifi0.network1","ax":"1","hidden":"0","password":"**REDACTED**","channel":"48","txpwr":"max","weakenable":"0","txbf":"3","signal":-98}],"code":0}

**http://192.168.31.1/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_diag_detail_all**

{"bsd":0,"info":[{"iftype":1,"ifname":"wl1","channelInfo":{"bandwidth":"0","bandList":["20","40"],"channel":11},"encryption":"psk2","device":"wifi1.network1","ax":"1","hidden":"0","txbf":"3","password":"**REDACTED**","bandwidth":"0","ssid":"RedSinInternet","channel":"11","status":"1","mode":"Master","txpwr":"max","signal":-97},{"iftype":2,"ifname":"wl0","channelInfo":{"bandwidth":"0","bandList":["20","40","80","160"],"channel":48},"encryption":"mixed-psk","device":"wifi0.network1","ax":"1","hidden":"0","txbf":"3","password":"**REDACTED**","bandwidth":"0","ssid":"RedSinInternet5","channel":"48","status":"1","mode":"Master","txpwr":"max","signal":-98},{"password":"**REDACTED**","ifname":"wl14","ssid":" 小米共享WiFi_A149","encryption":"psk2","status":0,"iftype":3,"enabled":"1"}],"code":0}

**Comment by fcoval** [comment]
I have turned off the 5G wifi network again and as you can see, the status of the switch in HomeAssistant is ON.

![03](https://user-images.githubusercontent.com/73198468/164965895-81e4882b-ca3b-4358-b597-b545a9839a8f.JPG)

As the switches do work on the router, **a simple sensor to Home Assistant that the Wi-Fi networks are activated or deactivated** would **solve the problem** (as the dual band sensor) and **change these two switchs**:
entity: switch.miwifi_xx_wifi_2_4g
entity: switch.miwifi_xx_wifi_5g
for buttons:
entity: button.miwifi_xx_wifi_2_4g
entity: button.miwifi_xx_wifi_5g

**Comment by dmamontov** [comment]
@fcoval You can see from your logs that the api returns that they are enabled. Those. component works correctly. Based on the number of devices is a bad idea. There is another option to check:

1. Go to page: http://192.168.31.1/cgi-bin/luci/;stok=**REDACTED**/web/setting/wifi
2. Disable any of the networks
3. Open the chrome debug panel: F12 (Mac: Cmd+Opt+I)
4. In the debug panel go to network
5. In the same place, enable the Fetch/XHR filter
6. Reload the page

All requests will appear in the debug panel. Get them and send me please.

It's definitely not the component. I checked on the same firmware version and everything works as it should. My instruction is the last resort in solving the problem.

**Comment by fcoval** [comment]
![10](https://user-images.githubusercontent.com/73198468/164972219-84f6fba7-a378-4524-8efa-b601ef460e9c.JPG)

http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/get_son_backhaul_mode
{"code":0,"mode":"0"}

http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/misystem/messages
{"messages":[],"count":0,"code":0}

http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/get_miscan_switch
{"enabled":0,"code":0}

http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_detail_all
{"bsd":0,"info":[{"ifname":"wl1","channelInfo":{"bandwidth":"0","bandList":["20","40"],"channel":11},"encryption":"psk2","bandwidth":"0","kickthreshold":"0","status":"1","mode":"Master","ssid":"RedSinInternet","weakthreshold":"0","device":"wifi1.network1","ax":"1","hidden":"0","password":**REDACTED*,"channel":"11","txpwr":"max","weakenable":"0","txbf":"3","signal":-97},{"ifname":"wl0","channelInfo":{"bandwidth":"0","bandList":["20","40","80","160"],"channel":"48"},"encryption":"mixed-psk","bandwidth":"0","kickthreshold":"0","status":"0","mode":"Master","ssid":**REDACTED*,"weakthreshold":"0","device":"wifi0.network1","ax":"1","hidden":"0","password":"000000000000000","channel":"48","txpwr":"max","weakenable":"0","txbf":"3","signal":0}],"code":0}

http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/get_miotrelay_switch
{"enabled":1,"code":0}

http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED*/api/xqsystem/country_code
{"current":"CN","list":[{"name":"中国大陆","code":"CN"},{"name":"香港地区","code":"HK"},{"name":"台湾地区","code":"TW"},{"name":"韩国","code":"KR"},{"name":"欧洲","code":"EU"}],"code":0}

**Comment by dmamontov** [comment]
http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_diag_detail_all

And you can also call the following method with the same actions. The API returns correctly.

**Comment by fcoval** [comment]
http://192.168.5.20/cgi-bin/luci/;stok=**REDACTED**/api/xqnetwork/wifi_diag_detail_all

{"bsd":0,"info":[{"iftype":1,"ifname":"wl1","channelInfo":{"bandwidth":"0","bandList":["20","40"],"channel":11},"encryption":"psk2","device":"wifi1.network1","ax":"1","hidden":"0","txbf":"3","password":"**REDACTED**","bandwidth":"0","ssid":"RedSinInternet","channel":"11","status":"1","mode":"Master","txpwr":"max","signal":-97},{"iftype":2,"ifname":"wl0","channelInfo":{"bandwidth":"0","bandList":["20","40","80","160"],"channel":"48"},"encryption":"mixed-psk","device":"wifi0.network1","ax":"1","hidden":"0","txbf":"3","password":"**REDACTED**","bandwidth":"0","ssid":"RedSinInternet5","channel":"48","status":"1","mode":"Master","txpwr":"max","signal":0},{"password":"**REDACTED**","ifname":"wl14","ssid":" 小米共享WiFi_A**REDACTED**","encryption":"psk2","status":0,"iftype":3,"enabled":"1"}],"code":0}

**Comment by dmamontov** [comment]
I'll test one theory and come back. If it is not confirmed, then what is the matter is very difficult to understand.

**Comment by fcoval** [comment]
If the component work well and I have a particular case, do not worry, I build a little solution in Home Assistant to me with 2 sensors about the number of devices, do not worry.

Many thanks Dimitry for your time and component.

**Comment by dmamontov** [comment]
@fcoval Well, the last attempt) Replace these 2 files and hass restart, if the problem goes away, I will add it to the release
[files.zip](https://github.com/dmamontov/hass-miwifi/files/8549803/files.zip)

**Comment by fcoval** [comment]
> @fcoval Well, the last attempt) Replace these 2 files and hass restart, if the problem goes away, I will add it to the release [files.zip](https://github.com/dmamontov/hass-miwifi/files/8549803/files.zip)

![11](https://user-images.githubusercontent.com/73198468/164988181-a0a364ec-047f-4c6a-bb4e-ff624ab93e0e.JPG)

**PERFECT !!!!** 
With these two files, **the switchs are working very well**.
Many thanks one more time.

**Comment by dmamontov** [comment]
Fine. Then I prepare the release

**Comment by dmamontov** [comment]
@fcoval https://github.com/dmamontov/hass-miwifi/releases/tag/v2.5.3

Can be updated
