### ISSUE TITLE
Add supports RB01

### ISSUE THREAD

**Issue by gydavid** [dmamontov/hass-miwifi#55]
Check list:
 * xqsystem/login: 🟢
 * xqsystem/init_info: 🟢
 * xqsystem/reboot: ⚪
 * xqnetwork/set_wifi: ⚪
 * xqnetwork/set_wifi_without_restart: ⚪
 * xqsystem/upgrade_rom: ⚪
 * xqsystem/flash_permission: ⚪
 * misystem/status: 🟢
 * xqsystem/check_rom_update: 🟢
 * xqnetwork/mode: 🟢
 * misystem/topo_graph: 🟢
 * xqnetwork/wan_info: 🟢
 * misystem/led: 🟢
 * xqnetwork/wifi_detail_all: 🟢
 * xqnetwork/wifi_diag_detail_all: 🟢
 * xqnetwork/avaliable_channels: 🟢
 * xqnetwork/wifi_connect_devices: 🟢
 * misystem/devicelist: 🟢
 * misystem/newstatus: 🟢
 * xqnetwork/wifiap_signal: 🟢

**Comment by dmamontov** [comment]
@gydavid https://github.com/dmamontov/hass-miwifi/releases/tag/v2.5.4

Added. Thank you.
