### ISSUE TITLE
Error in the Logs

### ISSUE THREAD

**Issue by Mangomc** [dmamontov/hass-miwifi#57]
Hey. Installed the integration yesterday. Everything works perfect. AX3600 CN. But I get one error in the logs.

`
The unit of sensor.miwifi_28_d1_27_70_d4_16_wan_download_speed is changing, got multiple {'MB/s', 'KB/s'}, generation of long term statistics will be suppressed unless the unit is stable and matches the unit of already compiled statistics (B/s). Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.miwifi_28_d1_27_70_d4_16_wan_upload_speed is changing, got multiple {'KB/s', 'B/s'}, generation of long term statistics will be suppressed unless the unit is stable and matches the unit of already compiled statistics (KB/s). Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
`

**Comment by dmamontov** [comment]
I'll fix it in the next version. Thank you.

**Comment by dmamontov** [comment]
@Mangomc https://github.com/dmamontov/hass-miwifi/releases/tag/v2.6.0

Problem solved.
