### ISSUE TITLE
FR: Consider home

### ISSUE THREAD

**Issue by Mangomc** [dmamontov/hass-miwifi#59]
Hey.

Im using Ur component to Arm and disarm my alarm panel. But my stupid Phone sometimtes disconnects from the WiFi for a few seconds. Is it possible to add a Consider home for that case like here:

https://www.home-assistant.io/integrations/device_tracker/

Thanks in advance :)

**Comment by dmamontov** [comment]
@Mangomc I'll add it in the next version

**Comment by Mangomc** [comment]
Great :)

**Comment by dmamontov** [comment]
@Mangomc https://github.com/dmamontov/hass-miwifi/releases/tag/v2.7.0

added)
