### ISSUE TITLE
[BUG] Some enitiy not available after update

### ISSUE THREAD

**Issue by AlterSb** [dmamontov/hass-miwifi#60]
**Describe the bug**
Some entities not available after update. Delete whole component and re-download won't fix.

![miwifiss](https://user-images.githubusercontent.com/36135345/167262261-0466569f-a806-4f51-8808-fa5e09c89af8.jpg)
![miwifi11](https://user-images.githubusercontent.com/36135345/167262262-92910de9-bc4a-4c70-a9ed-3845012e57f2.jpg)
![miwifi12](https://user-images.githubusercontent.com/36135345/167262263-01a6355a-3c6d-40c2-88bd-47902cfb8b5b.jpg)
![miwifi13](https://user-images.githubusercontent.com/36135345/167262264-df280836-b31c-463c-a122-fb81e2751086.jpg)

**Please complete the following information:**
 - HASS version: 2022.4.7
 - Component version 2.54/2.6.0
 - Router model : R3600
 - Router firmware version 3.0.22 (LV)

**Comment by dmamontov** [comment]
@AlterSb  as far as I can see, they are activated and not inaccessible, send diagnostic data

**Comment by AlterSb** [comment]
Here is diagnostic file. 

[config_entry-miwifi-6384fad6e505fb695294a228a0d372f5.json.txt](https://github.com/dmamontov/hass-miwifi/files/8645608/config_entry-miwifi-6384fad6e505fb695294a228a0d372f5.json.txt)

**Comment by dmamontov** [comment]
@AlterSb you are all right, go to the entity settings and enable them.  they are disabled by default.

**Comment by AlterSb** [comment]
Ahhh, thank you. Everything is worked fine. My bad, I didn't check it correctly.
