### ISSUE TITLE
An image of my routeur in Multimédia "caméra"

### ISSUE THREAD

**Issue by Nemesis24** [dmamontov/hass-miwifi#65]
![Sans titre](https://user-images.githubusercontent.com/25956796/168642447-d493953b-f22c-40d8-bbda-a27a837053cb.png)

I've got an image of my routeur as camera in multimedia panel.
I don't think this is normal, and if it's, i don't understand Why ??
Great Job !!
Thanks for all !!

**Comment by dmamontov** [comment]
@Nemesis24 This is not a bug, but just a camera object added so that you can easily reflect the image of the router in the cards.

Example:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/5955726/168648734-daf8579a-eef9-45a8-9370-6dce17ea8062.png">

**Comment by dmamontov** [comment]
I still thought about removing it. But I still do not understand if anyone except me uses it.

**Comment by Nemesis24** [comment]
Ok, that card is very cool so i think that it will be interesting to have it, but i think there is a way to do this whithout camera object.

**Comment by dmamontov** [comment]
@Nemesis24 Yet you are right. I'll remove it in the next release.

**Comment by dmamontov** [comment]
@Nemesis24 https://github.com/dmamontov/hass-miwifi/releases/tag/v2.7.3

Removed the camera, you can safely use images from the repository.
