### ISSUE TITLE
Questions ?? Miwifi repeater recognize password or invalid ip

### ISSUE THREAD

**Issue by Nemesis24** [dmamontov/hass-miwifi#71]
![Sans titre](https://user-images.githubusercontent.com/25956796/169343520-a1a2ae27-99e1-4384-b11a-fd5b01487583.png)

I've got my 2 MiWifi repeater recognize, but i can't give a password, this is not the same as the router.
When i give the same as the router I've got an "Invalid IP" message.

Can hass-miwifi detect the devices of the repeater?
If yes what is the way to give the good IP/Password?

Thanks for all.

**Comment by dmamontov** [comment]
and it is possible models of all devices?

**Comment by dmamontov** [comment]
and what's in the logs, if possible, in debug mode.

**Comment by dmamontov** [comment]
@Nemesis24 they have. unfortunately different protocol. I think it would be inappropriate to interfere with this in one integration. if you go to the address http://192.168.31.81/ what does it show?

But I'm still thinking about how to tie another protocol) But there is very little information in it. I’ll tell you a secret that I ordered a similar repeater for myself)

**Comment by Nemesis24** [comment]
Showing nothing "err connections refused"

**Comment by dmamontov** [comment]
@Nemesis24 https://github.com/dmamontov/hass-miwifi/releases/tag/v2.7.4

The release will exclude unsupported devices from discovery. Check please.

**Comment by Nemesis24** [comment]
This is good for me !!!

**Comment by dmamontov** [comment]
I think I will still make a new component that will support the current one, for repeaters, etc.
