### ISSUE TITLE
Add supports RB04(redmi ax5400 gaming)

### ISSUE THREAD

**Issue by tomaplutz** [dmamontov/hass-miwifi#73]
Check list:
 * xqsystem/login: 🟢
 * xqsystem/init_info: 🟢
 * misystem/status: 🟢
 * xqnetwork/mode: 🟢
 * misystem/topo_graph: 🟢
 * xqsystem/check_rom_update: 🔴
 * xqnetwork/wan_info: 🟢
 * misystem/led: 🟢
 * xqnetwork/wifi_detail_all: 🟢
 * xqnetwork/wifi_diag_detail_all: 🟢
 * xqnetwork/avaliable_channels: 🟢
 * xqnetwork/wifi_connect_devices: 🟢
 * misystem/devicelist: 🟢
 * xqnetwork/wifiap_signal: 🟢
 * misystem/newstatus: 🟢
 * xqsystem/reboot: ⚪
 * xqsystem/upgrade_rom: ⚪
 * xqsystem/flash_permission: ⚪
 * xqnetwork/set_wifi: ⚪
 * xqnetwork/set_wifi_without_restart: ⚪

**Comment by dmamontov** [comment]
@tomaplutz 

Wow, I was really looking forward to this router. Can you also attach an image of the router from the router's admin panel? and it's not on the site yet

Even after the release of the version, I will ask you to send diagnostic data, since the API has expanded in these versions of routers.

**Comment by tomaplutz** [comment]
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dmamontov** [comment]
@tomaplutz https://github.com/dmamontov/hass-miwifi/releases/tag/v2.7.5

Issued a release. Set up integration and please send diagnostic data.

**Comment by tomaplutz** [comment]
Many thanks was able to add ax5400 to home assistant

**Comment by tomaplutz** [comment]
Deployed. It is up and running

Many thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
