### ISSUE TITLE
[FEATURE REQUEST] - Skip device_tracker entities during set up

### ISSUE THREAD

**Issue by shift-del1** [dmamontov/hass-miwifi#78]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A checkbox during setup would be greatly appreciated to exclude the device_tracker entities and keep only the router relevant ones. I would like to be able to manage and supervise the router, but not interested in the connected devices. There are too many to disable them manually one by one, once the integration is set up.

**Describe alternatives you've considered**
Manually disabling and hiding them could be the option, but over 50 devices this is really painful.

Thanks in advance considering my request.

**Comment by dmamontov** [comment]
@shift-del1 https://github.com/dmamontov/hass-miwifi/releases/tag/v2.8.0
