### ISSUE TITLE
[BUG] R4A Guest Wifi switch created, but unavailable

### ISSUE THREAD

**Issue by velijv** [dmamontov/hass-miwifi#79]
**Describe the bug**

"Guest Wifi" switch is created on device page, but always unavailable. Sensor "Devices guest" is created and works to count guest devices. 

> **History**
> Unavailable
> **Logbook**
> No logbook events found.
> *This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.*

**Please complete the following information:**
 - HASS version: **2022.6.5**
 - Component version **2.7.5**
 - Router model **R4A**
 - Router firmware version **3.0.24**

Not related, but weird thing I discovered - all Xiaomi routers have a publicly accessible website for guest wifi, located at http://eu.api.miwifi.com/guest_wifi/portal?did=x-x-x-x-x which shows your guest wifi name for **everyone, no authentication needed** 😱. Scan your public IP using NMAP... edit: its port 8899 aka your.public.ip.address:8899

**Comment by dmamontov** [comment]
Send diagnostic data after enabling and disabling guest wifi.

**Comment by dmamontov** [comment]
Closed due to lack of activity.
