### ISSUE TITLE
[BUG] Some devices detected as "home" even when they definitly are not

### ISSUE THREAD

**Issue by FaserF** [dmamontov/hass-miwifi#81]
**Describe the bug**
Sometimes (I have hard times trying to reproduce it) my devices get recognized as home, even trough I am carrying them with me, so the definitly are not connected to the Wifi. It seems randomly and happenend minimum with two different devices to me.

I have tried looking in the looks, bug cant see anything relevant.

**Please complete the following information:**
 - HASS version: 2022.6.5
 - Component version 2.7.5
 - Router model AX3600
 - Router firmware version 1.1.19 CN

**Comment by dmamontov** [comment]
Unfortunately, this happens and it happens on the side of the router (devices remain in the API).
