### ISSUE TITLE
Connected clients are not shown on the MI-AX6000 Router

### ISSUE THREAD

**Issue by ffharaujo** [dmamontov/hass-miwifi#85]
**Describe the bug**
Connected clients are not shown on the MI-AX6000 Router

![ax6000](https://user-images.githubusercontent.com/33973087/176080202-cbf95ecb-f367-4e3d-bb39-02d3d030637a.png)

Thank you for your help

[config_entry-miwifi-a41cfc74f3440b7971cfabb1534f0db2.json.txt](https://github.com/dmamontov/hass-miwifi/files/8997260/config_entry-miwifi-a41cfc74f3440b7971cfabb1534f0db2.json.txt)

**Please complete the following information:**
 - HASS version: Home Assistant Core 2022.6.7
 - Component version: v2.8.0
 - Router model MI-AX6000
 - Router firmware version: 1.0.95

**Comment by ffharaujo** [comment]
Complementing the information, the router is configured in a Mesh network with an AX3000 and the same thing happens, if necessary I can upload the diagnostic file for that router as well.

Thanks for all

**Comment by dmamontov** [comment]
Good afternoon! Submit diagnostic data for all devices. Miwifi has a specificity that only the main device creates shows devices.

**Comment by ffharaujo** [comment]
Good morning, following diagnostic data of the AX3000.

Thanks for your help

[config_entry-miwifi-a41cfc74f3440b7971cfabb1534f0db2.json (2).txt](https://github.com/dmamontov/hass-miwifi/files/8999962/config_entry-miwifi-a41cfc74f3440b7971cfabb1534f0db2.json.2.txt)

**Comment by dmamontov** [comment]
@ffharaujo From the diagnostic data, it can be seen that one router is in access point mode and the second is a mesh. If your main router (which is DHCP) is not miwifi enabled, then I suggest enabling force mode in the integration settings. if it is with miwifi then add it first. The miwifi API gives detailed information only on the main device. As a workaround there is force_mode in the settings.

**Comment by ffharaujo** [comment]
Thanks for the reply, the network's DHCP is not the main router but my firewall, I don't know if this information is relevant.
Anyway, I'll follow your instructions and get back to you with the results.

Thank you for your help

**Comment by ffharaujo** [comment]
Good evening, the guide worked perfectly.
Success!

![MIWIFIOK](https://user-images.githubusercontent.com/33973087/176315763-2420d305-2081-412f-b99b-506c20cebdb4.png)

Thanks for your time in helping me
