### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wang3356** [dmamontov/hass-miwifi#86]
The message "Connected" is displayed on other network devices, but the message "This device has no entity" is displayed on mobile devices. You can see that the MAC address of the mobile phone is consistent with the total number of connected devices. I do not know what is the problem

**Comment by wang3356** [comment]
![image](https://user-images.githubusercontent.com/68215894/176106682-0961e443-e0b6-4ac0-b95f-fe5e8f3c8d9c.png)
![image](https://user-images.githubusercontent.com/68215894/176106865-68df06d6-a7b2-4349-8905-bc4d2ff56fa1.png)
![image](https://user-images.githubusercontent.com/68215894/176107145-9bebd147-c918-46d8-8e55-d3bebe356b8c.png)

**Comment by dmamontov** [comment]
@wang3356 Please send diagnostic data

**Comment by dmamontov** [comment]
Are mac addresses permanent on devices? Or change dynamically? almost all phones have dynamic ones by default and this should be turned off.

**Comment by wang3356** [comment]
Yes, thank you. I think I found the problem. It's not procedural
