### ISSUE TITLE
Add supports CR8808

### ISSUE THREAD

**Issue by wflijunnan** [dmamontov/hass-miwifi#87]
Check list:
 * xqsystem/login: 🟢
 * xqsystem/init_info: 🟢
 * misystem/status: 🟢
 * xqnetwork/mode: 🟢
 * misystem/topo_graph: 🟢
 * xqsystem/check_rom_update: 🟢
 * xqnetwork/wan_info: 🟢
 * misystem/led: 🟢
 * xqnetwork/wifi_detail_all: 🟢
 * xqnetwork/wifi_diag_detail_all: 🟢
 * xqnetwork/avaliable_channels: 🟢
 * xqnetwork/wifi_connect_devices: 🟢
 * misystem/devicelist: 🟢
 * xqnetwork/wifiap_signal: 🟢
 * misystem/newstatus: 🟢
 * xqsystem/reboot: ⚪
 * xqsystem/upgrade_rom: ⚪
 * xqsystem/flash_permission: ⚪
 * xqnetwork/set_wifi: ⚪
 * xqnetwork/set_wifi_without_restart: ⚪

**Comment by dmamontov** [comment]
@wflijunnan 

Added support
https://github.com/dmamontov/hass-miwifi/releases/tag/v2.8.1
