### ISSUE TITLE
[BUG] cannot config AX3200 connected to AX6 by Mesh (but AX3200 got an IP)

### ISSUE THREAD

**Issue by DavidFFerreira** [dmamontov/hass-miwifi#95]
[BUG] cannot config AX3200 connected to AX6 by Mesh (but AX3200 got an IP)

My AX3200 is connected to AX6 via MESH
I got into the interface via IPadress in both routers.
The integration works with AX6 IPAdress but i cannot add AX3200 IP Adress, the integration cannot find the AX3200 IPAdress that I gave him

![image](https://user-images.githubusercontent.com/32928749/188626385-3cb72262-f571-4450-90d4-c3e5c8e6893d.png)
![image](https://user-images.githubusercontent.com/32928749/188626130-155231f9-f1a7-486e-b058-54dd0f55fb55.png)
![image](https://user-images.githubusercontent.com/32928749/188626485-17a8146d-bf3b-417a-b4e4-7ee04f19bec3.png)
![image](https://user-images.githubusercontent.com/32928749/188626546-cb351452-349e-4ce5-9564-01b16bd011c7.png)

**Comment by dmamontov** [comment]
@DavidFFerreira Good afternoon! Have you tried changing password encryption?

Good afternoon! Have you tried changing password encryption? And please enable [debug logging](https://github.com/dmamontov/hass-miwifi/wiki/Diagnostics) and send the log.
