### ISSUE TITLE
Запрос статуса VPN и времени соединения

### ISSUE THREAD

**Issue by diandr6** [dmamontov/hass-miwifi#98]
Привет @dmamontov , добавь пожалуйста запрос `xqsystem/vpn_status`
Нужно для определение успешного подключения к провайдеру, буквально бинарный датчик и время соединения.
Спасибо)

Формат ответа такой:
![VPN_stat](https://user-images.githubusercontent.com/97342469/190712550-612f6c08-4a8f-447f-a4fc-e1b9e32853c9.PNG)

**Comment by dmamontov** [comment]
@diandr6 Думаю не проблема. Как появится время добавлю.

**Comment by dmamontov** [comment]
@diandr6 Добавил поддержку: https://github.com/dmamontov/hass-miwifi/releases/tag/v2.9.0
